### ISSUE TITLE
Example of using this?

### ISSUE THREAD

**Issue by thihaaung6245** [nickolanack/ios-mapkit-groundoverlay#1]
Hi,I am trying to convert this code in swift.So,I really need complete example project of using this with kml.Any Help Please?

**Comment by nickolanack** [comment]
Sorry I never noticed your question. This library does not parse kmls and only handles the rendering of ground overlays assuming that the kml values have already been extracted, and the image is included with compiled ios project.

I'll try to cobble together a working example for this library. in the meantime... 

here is a kml that I've used

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<GroundOverlay>
    <name>Okanagan Mnt Park</name>
    <color>91ffffff</color>
    <Icon>
        <href>files/ok-mnt-park.png</href>
        <viewBoundScale>0.75</viewBoundScale>
    </Icon>
    <LatLonBox>
        <north>49.78804779230693</north>
        <south>49.66112454176398</south>
        <east>-119.5450127722225</east>
        <west>-119.7354134660719</west>
        <rotation>2.071346006143104</rotation>
    </LatLonBox>
</GroundOverlay>
</kml>
```

here is the image that goes with it. 
![ok-mnt-park](https://cloud.githubusercontent.com/assets/8965209/19050178/53087268-8962-11e6-97bb-ef7a7ef95f49.png)

**Comment by thihaaung6245** [comment]
I have convert your code into Swift.I will post solution here.Thanks for your help.Your ground overlay work perfectly well

**Comment by nickolanack** [comment]
cool
